const tempMovies = () => {
  const movies = [];
  const movie1 = {"Title":"Jaws","Year":"1975","Rated":"PG","Released":"20 Jun 1975","Runtime":"124 min","Genre":"Adventure, Mystery, Thriller","Director":"Steven Spielberg","Writer":"Peter Benchley, Carl Gottlieb","Actors":"Roy Scheider, Robert Shaw, Richard Dreyfuss","Plot":"When a killer shark unleashes chaos on a beach community off Cape Cod, it's up to a local sheriff, a marine biologist, and an old seafarer to hunt the beast down.","Language":"English","Country":"United States","Awards":"Won 3 Oscars. 15 wins & 20 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BMmVmODY1MzEtYTMwZC00MzNhLWFkNDMtZjAwM2EwODUxZTA5XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.1/10"},{"Source":"Rotten Tomatoes","Value":"97%"},{"Source":"Metacritic","Value":"87/100"}],"Metascore":"87","imdbRating":"8.1","imdbVotes":"628,138","imdbID":"tt0073195","Type":"movie","DVD":"14 Jun 2005","BoxOffice":"$265,859,065","Production":"N/A","Website":"N/A","Response":"True"}
  movies.push(movie1);
  const movie2 = {"Title":"Indiana Jones and the Temple of Doom","Year":"1984","Rated":"PG","Released":"23 May 1984","Runtime":"118 min","Genre":"Action, Adventure","Director":"Steven Spielberg","Writer":"Willard Huyck, Gloria Katz, George Lucas","Actors":"Harrison Ford, Kate Capshaw, Ke Huy Quan","Plot":"In 1935, Indiana Jones is tasked by Indian villagers with reclaiming a rock stolen from them by a secret cult beneath the catacombs of an ancient palace.","Language":"English, Sinhala, Hindi","Country":"United States","Awards":"Won 1 Oscar. 11 wins & 21 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BYzgzMTIzNzctNmNiZC00ZDYyLWJjNzktMmQ2MDM2ZDkwZGVhXkEyXkFqcGdeQXVyMjM4MzQ4OTQ@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.5/10"},{"Source":"Rotten Tomatoes","Value":"77%"},{"Source":"Metacritic","Value":"57/100"}],"Metascore":"57","imdbRating":"7.5","imdbVotes":"512,702","imdbID":"tt0087469","Type":"movie","DVD":"13 May 2008","BoxOffice":"$179,870,271","Production":"N/A","Website":"N/A","Response":"True"}
  movies.push(movie2);
  const movie3 =  {"Title":"Mean Girls","Year":"2004","Rated":"PG-13","Released":"30 Apr 2004","Runtime":"97 min","Genre":"Comedy","Director":"Mark Waters","Writer":"Rosalind Wiseman, Tina Fey","Actors":"Lindsay Lohan, Jonathan Bennett, Rachel McAdams","Plot":"Cady Heron is a hit with The Plastics, the A-list girl clique at her new school, until she makes the mistake of falling for Aaron Samuels, the ex-boyfriend of alpha Plastic Regina George.","Language":"English, German, Vietnamese, Swahili","Country":"United States, Canada","Awards":"7 wins & 25 nominations","Poster":"https://m.media-amazon.com/images/M/MV5BMjE1MDQ4MjI1OV5BMl5BanBnXkFtZTcwNzcwODAzMw@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.1/10"},{"Source":"Rotten Tomatoes","Value":"84%"},{"Source":"Metacritic","Value":"66/100"}],"Metascore":"66","imdbRating":"7.1","imdbVotes":"400,967","imdbID":"tt0377092","Type":"movie","DVD":"21 Sep 2004","BoxOffice":"$86,058,055","Production":"N/A","Website":"N/A","Response":"True"};
  movies.push(movie3);
  const movie4 = {"Title":"Freaky Friday","Year":"2003","Rated":"PG","Released":"06 Aug 2003","Runtime":"97 min","Genre":"Comedy, Family, Fantasy","Director":"Mark Waters","Writer":"Mary Rodgers, Heather Hach, Leslie Dixon","Actors":"Jamie Lee Curtis, Lindsay Lohan, Mark Harmon","Plot":"An overworked mother and her daughter do not get along. When they switch bodies, each is forced to adapt to the other's life for one freaky Friday.","Language":"English, Mandarin","Country":"United States","Awards":"5 wins & 11 nominations","Poster":"https://m.media-amazon.com/images/M/MV5BYmU4NTk4OWYtMjE4My00MGVkLTgwY2EtZTZjN2YyOGFiMDQ0L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"6.3/10"},{"Source":"Rotten Tomatoes","Value":"88%"},{"Source":"Metacritic","Value":"70/100"}],"Metascore":"70","imdbRating":"6.3","imdbVotes":"144,993","imdbID":"tt0322330","Type":"movie","DVD":"21 Dec 2004","BoxOffice":"$110,230,332","Production":"N/A","Website":"N/A","Response":"True"};
  movies.push(movie4);

  return(movies);
}

export default tempMovies